{% set name = "wagtailmedia" %}
{% set version = "0.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtailmedia-{{ version }}.tar.gz
  sha256: 8e1406f432d159e195f5627eec187ec91b02389b9a97dc9ae214a74305592aa3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - wagtail >=4.1
    - django >=3.2

test:
  imports:
    - wagtailmedia
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/torchbox/wagtailmedia
  summary: A Wagtail module for audio and video files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
