{% set name = "wagtailmedia" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/wagtailmedia-{{ version }}.tar.gz
  sha256: 8f7e40a3b672a4648224df3dadf3e4aafc4785d47f92efac5a120af7a26b871f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - django-ninja
    - ninja-python
    - pydantic
    - django-taggit
    - djangorestframework
    - python >={{ python_min }}
    - wagtail >=7.0
    - django >=5.2

test:
  imports:
    - wagtailmedia
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/torchbox/wagtailmedia
  summary: A Wagtail module for audio and video files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
